### PR TITLE
Fix spelling of ENCRYPTION_KEY

### PR DESCRIPTION
**Pull request by ajlennon**

### CODE REVIEW

**Comment by mpous** [comment]
LGTM

**Comment by mpous** [comment]
Change-type: minor

**Comment by mpous** [comment]
@balena-ci I self-certify!

**Comment by ajlennon** [comment]
Thanks @mpous - there are a couple of CI errors here I don't understand. Is there anything I need to do ?

**Comment by mpous** [comment]
@ajlennon do you think you can retry the PR using this contribution guidelines with the  `Change-type` in the comment? https://github.com/balena-os/meta-balena/blob/master/CONTRIBUTING.md#contributing

**Comment by ajlennon** [comment]
Let me try...

**Comment by ajlennon** [comment]
How about that @mpous ?

**Comment by mpous** [comment]
LGTM

**Pull request closed without merging**
